
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohit
 */
public class Forgot extends javax.swing.JFrame {

    private String user;

    /**
     * Creates new form Forgot
     */
    public Forgot() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotpasspanel = new javax.swing.JPanel();
        fpasswordheading = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        sercurity = new javax.swing.JLabel();
        anssecurity = new javax.swing.JLabel();
        securityoption = new javax.swing.JComboBox<>();
        usernametext = new javax.swing.JTextField();
        answersecurity = new javax.swing.JTextField();
        newpass = new javax.swing.JLabel();
        confpassword = new javax.swing.JLabel();
        resetpass = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        returnlogin = new javax.swing.JLabel();
        newuser = new javax.swing.JLabel();
        tip = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        headingpanel3 = new javax.swing.JPanel();
        pccoeicon3 = new javax.swing.JLabel();
        pccoename3 = new javax.swing.JLabel();
        itsaname3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        forgotpasspanel.setBackground(new java.awt.Color(44, 62, 80));
        forgotpasspanel.setFocusCycleRoot(true);
        forgotpasspanel.setFocusTraversalPolicyProvider(true);

        fpasswordheading.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        fpasswordheading.setForeground(new java.awt.Color(255, 255, 255));
        fpasswordheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fpasswordheading.setText("Forgot password?");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");

        sercurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sercurity.setForeground(new java.awt.Color(255, 255, 255));
        sercurity.setText("Security Question:");

        anssecurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anssecurity.setForeground(new java.awt.Color(255, 255, 255));
        anssecurity.setText("Answer:");

        securityoption.setBackground(new java.awt.Color(108, 122, 137));
        securityoption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        securityoption.setMaximumRowCount(20);
        securityoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your childhood nickname?", "Who is your favourite actor?", "What is your school name?", "Who is your favourite actress?", "Which is your favourite animal?", "What is your pet name?", "What is name of your favourite movie?", "What is your college name?", "What is your crush name?", "" }));
        securityoption.setToolTipText("Enter a security question which you should remember if you forgot your password or username");
        securityoption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        securityoption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        securityoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityoptionActionPerformed(evt);
            }
        });

        usernametext.setBackground(new java.awt.Color(108, 122, 137));
        usernametext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernametext.setToolTipText("Enter Mobile Number or Email id");
        usernametext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextActionPerformed(evt);
            }
        });

        answersecurity.setBackground(new java.awt.Color(108, 122, 137));
        answersecurity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answersecurity.setToolTipText("Enter answer of the security question you choosed");
        answersecurity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        answersecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answersecurityActionPerformed(evt);
            }
        });

        newpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpass.setForeground(new java.awt.Color(255, 255, 255));
        newpass.setText("New Password:");

        confpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confpassword.setForeground(new java.awt.Color(255, 255, 255));
        confpassword.setText("Confirm Password:");

        resetpass.setBackground(new java.awt.Color(0, 204, 0));
        resetpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetpass.setText("Reset Password");
        resetpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        resetpass.setContentAreaFilled(false);
        resetpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetpass.setOpaque(true);
        resetpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetpassMousePressed(evt);
            }
        });
        resetpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetpassActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cancel.setContentAreaFilled(false);
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setFocusCycleRoot(true);
        cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel.setLabel("Cancel");
        cancel.setOpaque(true);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        returnlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnlogin.setForeground(new java.awt.Color(255, 255, 0));
        returnlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnlogin.setText("Return to login?");
        returnlogin.setToolTipText("Login ");
        returnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnloginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnloginMousePressed(evt);
            }
        });

        newuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newuser.setForeground(new java.awt.Color(255, 255, 0));
        newuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newuser.setText("Create New User");
        newuser.setToolTipText("Signup");
        newuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });

        tip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tip.setForeground(new java.awt.Color(255, 255, 0));
        tip.setText("**Please enter your username and security question");

        newpassword.setBackground(new java.awt.Color(108, 122, 137));
        newpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpassword.setToolTipText("Should atleast contain a symbol & a digit");
        newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordActionPerformed(evt);
            }
        });

        confirmpassword.setBackground(new java.awt.Color(108, 122, 137));
        confirmpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmpassword.setToolTipText("Re-enter password");

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Validate");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotpasspanelLayout = new javax.swing.GroupLayout(forgotpasspanel);
        forgotpasspanel.setLayout(forgotpasspanelLayout);
        forgotpasspanelLayout.setHorizontalGroup(
            forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(fpasswordheading, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotpasspanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sercurity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anssecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confpassword))
                                .addGap(26, 26, 26)
                                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotpasspanelLayout.createSequentialGroup()
                                        .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(resetpass, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(confirmpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(newpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(securityoption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(answersecurity))
                                            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                                                .addComponent(returnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(4, 4, 4))))
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        forgotpasspanelLayout.setVerticalGroup(
            forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fpasswordheading, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tip)
                .addGap(15, 15, 15)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sercurity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityoption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anssecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answersecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpass)
                    .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetpass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotpasspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(forgotpasspanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/forgotpasswordicon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        headingpanel3.setBackground(new java.awt.Color(248, 148, 6));
        headingpanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        pccoeicon3.setBackground(new java.awt.Color(0, 0, 0));
        pccoeicon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/PCCOE_LOGO.jpg"))); // NOI18N

        pccoename3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pccoename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pccoename3.setText("PCET'S PIMPRI CHINCHWAD COLLEGE OF ENGINEERING, PUNE");

        itsaname3.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        itsaname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itsaname3.setText("INFORMATION TECHNOLOGY STUDENT ASSOCIATION (ITSA)");

        javax.swing.GroupLayout headingpanel3Layout = new javax.swing.GroupLayout(headingpanel3);
        headingpanel3.setLayout(headingpanel3Layout);
        headingpanel3Layout.setHorizontalGroup(
            headingpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingpanel3Layout.createSequentialGroup()
                .addComponent(pccoeicon3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(headingpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pccoename3, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itsaname3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headingpanel3Layout.setVerticalGroup(
            headingpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pccoeicon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headingpanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(pccoename3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itsaname3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(forgotpasspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgotpasspanel, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void securityoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityoptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityoptionActionPerformed

    private void usernametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextActionPerformed

    private void answersecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answersecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answersecurityActionPerformed

    private void resetpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpassMousePressed

    }//GEN-LAST:event_resetpassMousePressed

    private void resetpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetpassActionPerformed
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Connection Successful");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itsa?useTimezone=true&serverTimezone=UTC", "root","M#mohit2002");
            // JOptionPane.showConfirmDialog(null, "Connection Successful");
            //String name = "mohitjadhav";
            Statement stmnt= con.createStatement();
                if(String.valueOf(newpassword.getPassword()).equals(String.valueOf(confirmpassword.getPassword()))){
                    if(!((String.valueOf(newpassword.getPassword()).isEmpty()) && (String.valueOf(confirmpassword.getPassword()).isEmpty()))){
                        String query = "UPDATE `users` SET `userpassword`= ? WHERE username = ?";
                        PreparedStatement ps = con.prepareStatement(query);
                        ps.setString(1,String.valueOf(newpassword.getPassword()));
                        ps.setString(2,user);
                        int executeUpdate = ps.executeUpdate();
                        if(executeUpdate>0)
                        {
                            JOptionPane.showMessageDialog(null,"Password changed...Try login");
                            new LoginFinal().setVisible(true);
                            this.dispose();                    
                        }
                        else
                        {         
                            JOptionPane.showMessageDialog(null,"Please try again");
                        }
                    }
                    else{
                              JOptionPane.showMessageDialog(null, "Please enter new password");
                        }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Password should match the confirm password");
                    newpassword.setText("");
                    confirmpassword.setText("");
                    }
                
            }
        catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null,"Connection Failed");
        } catch (SQLException ex) {
            //  System.out.println();
            JOptionPane.showMessageDialog(null,"Connection Failed");

        }
    }//GEN-LAST:event_resetpassActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        new LoginFinal().setVisible(true);

    }//GEN-LAST:event_cancelActionPerformed

    private void returnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnloginMouseClicked
        this.dispose();
        new LoginFinal().setVisible(true);
    }//GEN-LAST:event_returnloginMouseClicked

    private void returnloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnloginMousePressed
        this.dispose();
        new LoginFinal().setVisible(true);
    }//GEN-LAST:event_returnloginMousePressed

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        this.dispose();
        new SignUp().setVisible(true);
    }//GEN-LAST:event_newuserMouseClicked

    private void newpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Connection Successful");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itsa?useTimezone=true&serverTimezone=UTC", "root","M#mohit2002");
            // JOptionPane.showConfirmDialog(null, "Connection Successful");
            //String name = "mohitjadhav";
            Statement stmnt= con.createStatement();
            String query = ("SELECT * FROM `users` where `username`=? and `answersecurityquestion`=? ");
            PreparedStatement ps = con.prepareStatement(query);
            user = usernametext.getText();
            ps.setString(1,user);
            ps.setString(2,String.valueOf(answersecurity.getText()));
            ResultSet executeQuery = ps.executeQuery();
            if(executeQuery.next()){
                JOptionPane.showMessageDialog(null,"User exist...Enter new password");
            }
            else{
                JOptionPane.showMessageDialog(null,"Check credentials...User not found");
                usernametext.setText("");
                answersecurity.setText("");
            }
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null,"Connection Failed!");
        } catch (SQLException ex) {
            //  System.out.println();
            JOptionPane.showMessageDialog(null,"Connection Failed");

        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anssecurity;
    private javax.swing.JTextField answersecurity;
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel confpassword;
    private javax.swing.JPanel forgotpasspanel;
    private javax.swing.JLabel fpasswordheading;
    private javax.swing.JPanel headingpanel3;
    private javax.swing.JLabel itsaname3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newpass;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JLabel newuser;
    private javax.swing.JLabel pccoeicon3;
    private javax.swing.JLabel pccoename3;
    private javax.swing.JButton resetpass;
    private javax.swing.JLabel returnlogin;
    private javax.swing.JComboBox<String> securityoption;
    private javax.swing.JLabel sercurity;
    private javax.swing.JLabel tip;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
